### ISSUE TITLE
listenlocalhost test fails on ARM Linux

### ISSUE THREAD

**Issue by petevine** [ebfull/pcap#49]
The same issue [didn't allow](https://www.reddit.com/r/rust/comments/4fv9qi/rust_passivedns_monitoring_utility/d2fwo0w) me to use passivedns-rs.
The final part of the strace looks like this:

```shell
socket(PF_PACKET, SOCK_DGRAM, 768)      = 3
ioctl(3, SIOCGIFINDEX, {ifr_name="lo", ifr_index=1}) = 0
setsockopt(3, SOL_PACKET, PACKET_AUXDATA, [1], 4) = 0
getsockopt(3, SOL_PACKET, PACKET_HDRLEN, [36], [4]) = 0
setsockopt(3, SOL_PACKET, PACKET_VERSION, [2], 4) = 0
setsockopt(3, SOL_PACKET, PACKET_RESERVE, [4], 4) = 0
setsockopt(3, SOL_PACKET, PACKET_RX_RING, "\0\0\2\0\20\0\0\0\0\0\2\0\20\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 28) = 0
mmap2(NULL, 2097152, PROT_READ|PROT_WRITE, MAP_SHARED, 3, 0) = 0xb6ae1000
setsockopt(3, SOL_SOCKET, SO_ATTACH_FILTER, "\1\0\0\0\374\341\352\266", 8) = 0
fcntl64(3, F_GETFL)                     = 0x2 (flags O_RDWR)
fcntl64(3, F_SETFL, O_RDWR|O_NONBLOCK)  = 0
recv(3, 0xbeb81234, 1, MSG_TRUNC)       = -1 EAGAIN (Resource temporarily unavailable)
fcntl64(3, F_SETFL, O_RDWR)             = 0
setsockopt(3, SOL_SOCKET, SO_ATTACH_FILTER, "\32\0\0\0008\345\362\266", 8) = 0
setsockopt(3, SOL_PACKET, PACKET_RX_RING, {block_size=0, block_nr=0, frame_size=0, frame_nr=0}, 16) = -1 EINVAL (Invalid argument)
````

Was using crate version `0.5.6` and rust `1.10`.

The `savefile` test also fails, like this:
```rust
# RUST_BACKTRACE=1 target/debug/examples/savefile
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: TimeoutExpired', src/libcore/result.rs:785
stack backtrace:
   1: 0xb6f72a57 - std::sys::backtrace::tracing::imp::write::h82353b94d9957b5a
   2: 0xb6f73a97 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hd08c9fd28a21a931
   3: 0xb6f7374f - std::panicking::default_hook::h9f5ce461fe95b992
   4: 0xb6f73c8b - std::panicking::on_panic::h72ebaabe6df491a5
   5: 0xb6f748d7 - std::sys_common::unwind::begin_unwind_inner::hf3b309d035c8a630
   6: 0xb6f75263 - std::sys_common::unwind::begin_unwind_fmt::h93bb4d1d4be19775
   7: 0xb6f751af - rust_begin_unwind
   8: 0xb6f81133 - core::panicking::panic_fmt::h5f695b461e45588f
   9: 0xb6f688fb - core::result::unwrap_failed::h04300aeb8da3ddc6
                at src/libcore/macros.rs:29
  10: 0xb6f6abfb - _<std..result..Result<T, E>>::unwrap::hbf942d7177bccc5a
                at src/libcore/result.rs:723
  11: 0xb6f682eb - savefile::main::heb6383c973898e7a
                at examples/savefile.rs:14
  12: 0xb6f75c03 - std::sys_common::unwind::try::hcfd1e9f9a0a0d375
  13: 0xb6f758ef - std::rt::lang_start::h801b666f82634252
  14: 0xb6f6bbcf - main
  15: 0xb6dd0631 - __libc_start_main
````

**Comment by petevine** [comment]
@ebfull Any suggestions? BTW, does this crate put any constraints on the underlying library version?

**Comment by ebfull** [comment]
Not sure! I don't have an ARM development device to test with. :(

**Comment by petevine** [comment]
It's your regular ARM Linux and the `pcap` library works OK with the C version of passivedns. That's why I asked about the library version the crate might expect.

**Comment by ebfull** [comment]
@petevine Why closed?
